### ISSUE TITLE
May not need to use request for eta

### ISSUE THREAD

**Issue by t-wy** [nubotz/hk9busbot#1]
The URL for the mobile (app) version of the KMB app require a simpler request method, which does not need any header or content to be passed.
http://etav3.kmb.hk/?action=geteta&lang=tc&route=_route_&bound=_bound_&stop=_BSICode_&stop_seq=_seq_&serviceType=_serviceType_

The URL for the desktop version (as in your code shown):
http://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx/?action=get_ETA&lang=1

**Comment by wingyintang** [comment]
For some decovery only.
